# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/http/authproxy/v2alpha1/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/http/authproxy/v2alpha1/config.proto',
  package='istio.envoy.config.filter.http.authproxy.v2alpha1',
  syntax='proto3',
  serialized_pb=_b('\n8envoy/config/filter/http/authproxy/v2alpha1/config.proto\x12\x31istio.envoy.config.filter.http.authproxy.v2alpha1\"(\n\x0c\x46ilterConfig\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\tB:Z8istio.io/api/envoy/config/filter/http/authproxy/v2alpha1b\x06proto3')
)




_FILTERCONFIG = _descriptor.Descriptor(
  name='FilterConfig',
  full_name='istio.envoy.config.filter.http.authproxy.v2alpha1.FilterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='istio.envoy.config.filter.http.authproxy.v2alpha1.FilterConfig.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='istio.envoy.config.filter.http.authproxy.v2alpha1.FilterConfig.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['FilterConfig'] = _FILTERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterConfig = _reflection.GeneratedProtocolMessageType('FilterConfig', (_message.Message,), dict(
  DESCRIPTOR = _FILTERCONFIG,
  __module__ = 'envoy.config.filter.http.authproxy.v2alpha1.config_pb2'
  # @@protoc_insertion_point(class_scope:istio.envoy.config.filter.http.authproxy.v2alpha1.FilterConfig)
  ))
_sym_db.RegisterMessage(FilterConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z8istio.io/api/envoy/config/filter/http/authproxy/v2alpha1'))
# @@protoc_insertion_point(module_scope)
